name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP with extensions
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Execute tests
      run: composer run-script test
